
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "release/v3.0.0"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Helsinki"
    commit-message:
      prefix: "chore(github-actions)"
      include: "scope"
    reviewers:
      - "kare"
    labels:
      - "github-actions"
      - "dependencies"
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "release/v3.0.0"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Helsinki"
    commit-message:
      prefix: "chore(gradle)"
      include: "scope"
    reviewers:
      - "kare"
    labels:
      - "gradle"
      - "dependencies"

