language: java
jdk:
- openjdk8
dist: trusty
sudo: true
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
install:
  - ./gradlew --console plain build --exclude-task test --exclude-task integrationTest build
jobs:
  include:
  - stage: Tests
    name: Unit Tests
    script:
    - "./gradlew test --stacktrace --info"
  - stage: Tests
    name: Integration Tests
    script:
    - sudo /etc/init.d/mysql stop
    - sudo sysctl fs.inotify.max_user_watches=524288; sudo sysctl -p
    - git clone https://github.com/streamr-dev/streamr-docker-dev.git
    - sudo ifconfig docker0 10.200.10.1/24
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - "$TRAVIS_BUILD_DIR/streamr-docker-dev/streamr-docker-dev/bin.sh start"
    - "$TRAVIS_BUILD_DIR/streamr-docker-dev/streamr-docker-dev/bin.sh log -f engine-and-editor broker-node-storage-1 broker-node-no-storage-1 broker-node-no-storage-2 &"
    - "$TRAVIS_BUILD_DIR/streamr-docker-dev/streamr-docker-dev/bin.sh wait"
    - "./gradlew integrationTest --stacktrace --info"
  - stage: Tests
    name: Source formatting
    script:
      - ./gradlew --console plain --info spotlessCheck
#  - stage: Tests
#    name: Cross-client tests
#    script:
#    - ".travis_scripts/cross-client-tests.sh"
